name: open_meteo_api
description: "A new Flutter package project."
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  http: ^1.2.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
